# Generated by Django 4.2 on 2024-06-11 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodo',
            name='fecha_final',
        ),
        migrations.RemoveField(
            model_name='periodo',
            name='fecha_inicio',
        ),
    ]
