# Generated by Django 4.2 on 2024-06-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_periodo_fecha_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallenota',
            name='nota1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detallenota',
            name='nota2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detallenota',
            name='observacion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='detallenota',
            name='recuperacion',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
