# Generated by Django 4.2 on 2024-06-16 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_detallenota_nota1_alter_detallenota_nota2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallenota',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
